### ISSUE TITLE
 Faster R-CNN 학습

### ISSUE THREAD

**Issue by peternara** [peternara/Study#4]
* c++ 로 python 모듈을 호출

* add
> * _init_paths.py
> * tools/demo.py 를 class 형태로 변환 --> faster_rcnn.py
> * C++ 에서 faster_rcnn.py 함수를 호출하는데 성공
> * 주의)
>> * _init_paths.py 를 두개의 패스 수정해야? -> 어느 dir에서 되려면? - 밑의 두부분 수정하면 됨
>>> * caffe_path = osp.join(this_dir, '** /../opt/py-faster-rcnn/ **', 'caffe-fast-rcnn', 'python')
>>> * lib_path = osp.join(this_dir, '** /../opt/py-faster-rcnn/ **', 'lib')
> * error
>> * 1 - Unable to import embed modulefail FASTER_RCNN python class instancePCA ?
>>> * ls -al /../opt/ 했을때,  ** caffe -> py-faster-rcnn/caffe-fast-rcnn/ ** 심볼릭링크가 되어야한다.
>> * 2 - c모듈과 python 모듈에 대한 GPU ID를 일치시켜야한다. - 
>>> * 서로 따로 호출하기 때문에 실수하기가 쉽다.

* 학습
> * 1th 명령어 (alternating optimization): ./tools/train_faster_rcnn_alt_opt.py --gpu 1 --net_name VGG16  --weights data/imagenet_models/VGG16.v2.caffemodel --imdb x_20151129 --cfg experiments/cfgs/faster_rcnn_alt_opt.yml
> * 2th 명령어 (approximate joint training): ./tools/train_net.py --gpu 1 --solver models/VGG16/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb x_20151129 --iters 70000 --cfg experiments/cfgs/faster_rcnn_end2end.yml
>> * 1th vs 2th -> faster (~ 1.5x speedup) training times and similar detection accuracy.

**Comment by peternara** [comment]
fast r-cnn처럼 미리 data를 생성할 필요가없다.

**Comment by peternara** [comment]
* ./tools/train_net.py --gpu 1 --solver models/ZF/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/ZF.v2.caffemodel --imdb  x_20160106 --iters 70000 --cfg ./experiments/cfgs/faster_rcnn_end2end.yml

* ./tools/train_net.py --gpu 1 --solver models/VGG16/faster_rcnn_end2end/solver.prototxt --weights data/imagenet_models/VGG16.v2.caffemodel --imdb x_20160512 --iters 70000 --cfg ./experiments/cfgs/faster_rcnn_end2end.yml

**Comment by peternara** [comment]
에러

one
Preparing training data...
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "./tools/train_faster_rcnn_alt_opt.py", line 122, in train_rpn
    roidb, imdb = get_roidb(imdb_name)
  File "./tools/train_faster_rcnn_alt_opt.py", line 67, in get_roidb
    roidb = get_training_roidb(imdb)
  File "/data_ssd1/naver/opt/py-faster-rcnn/tools/../lib/fast_rcnn/train.py", line 122, in get_training_roidb
    rdl_roidb.prepare_roidb(imdb)
  File "/data_ssd1/naver/opt/py-faster-rcnn/tools/../lib/roi_data_layer/roidb.py", line 27, in prepare_roidb
    roidb[i]['image'] = imdb.image_path_at(i)
IndexError: list index out of range
^CTraceback (most recent call last):
  File "./tools/train_faster_rcnn_alt_opt.py", line 241, in <module>
    rpn_stage1_out = mp_queue.get()
  File "/usr/lib/python2.7/multiprocessing/queues.py", line 117, in get
    res = self._recv()
KeyboardInterrupt

이전에 만들었던 trainig db 문제 예) rm data/cache/x_20160514_gt_roidb.pkl

**Comment by peternara** [comment]
*  width/height 비율이 큰 이미지 - lib 에서 1000기준으로 리사이즈하는듯.

print ----

im_size: (1000.0, 81.0)
scale: 0.109289616346
height, width: (63, 6)
rpn: gt_boxes.shape (45, 5)
rpn: gt_boxes [[  5.50819664e+01   2.84153008e+00   8.01092911e+01   3.94535522e+01

> 그 이미지를 제거

**Comment by peternara** [comment]
>:~/users/peternara/face_detection/faster_rcnn$ ./main.out t1.jpg
 init call
../faster_rcnn/model/vgg_face_deploy.prototxt
../faster_rcnn/model/vgg16_faster_rcnn_iter_70000.caffemodel

** fail FASTER_RCNN python class instance **

모델 패스가 안맞는것임.
